### ISSUE TITLE
[Feature Request] Allow the user to specify the offset for the "cursor" tracker  

### ISSUE THREAD

**Issue by xDinosaurus** [garzj/gjs-pointer-tracker#1]
I'm using this extension to screen share with a tablet a-la apple sidecar. I would like to be able to offset the "cursor" tracker so that it appears directly under my native cursor, so that I can leave this extension on constantly. If I could decide how the cursor is offset, it would allow me to do this.

**Comment by garzj** [comment]
The offset of the cursor is actually an issue I noticed beforehand, I fixed it in 1bed7fb now.
Because your use-case seems to be the exact same as mine, I added the option to only enable the cursor tracker while screen sharing in v1.1.0. I took some inspiration from [here](https://github.com/marcinjahn/gnome-do-not-disturb-while-screen-sharing-or-recording-extension). Let me know if it works for you!

**Comment by xDinosaurus** [comment]
Awesome! Just installed the new version, thanks for the quick update!
